server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flat
    driver-class-name: org.postgresql.Driver
    username: app
    password: parola
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
jwt:
  secret: 70B12EA3F894B7F22FC57F33166161AB59F9D269CBF7D492388ECDB8CB267503
